version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: compagnie_creole
      MYSQL_ROOT_PASSWORD: BT0a85Rc7PjVe9HT7SuT
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  backend:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: backend
    restart: always
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: BT0a85Rc7PjVe9HT7SuT
      DB_NAME: compagnie_creole
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "8080:80"

volumes:
  db_data:
